# TODO LIST
# Make a graph to see how correllated weather features are?
# Implement exponential decay
# Look for variables that are different across groupings
#
#
```{r, results="hide", message=F, echo=F}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
rm(list = ls())
library(tidyverse)
library(mvtnorm)
library(ggplot2)
library(glmnet)
library(mombf)
library(rstanarm)
library(caret)
library(viridis)
library(splitTools)
library(ggpubr)
PATH = "/home/carneca/Documents/College/masters/semester1/stats/assignment/fmc_prediction/code"
```
```{r, post_processing functions}
compute_r2 <- function(true, pred){
  r2 <- 1 - sum((pred - true)^2)/sum((true - mean(true))^2)
  return(r2)
}

colmeans <- function(frame){
  for (col in names(frame)){
    print(paste(col, "R2:", round(mean(frame[,col]), digits=3)))
  }
}

process <- function(df, target, drop_cols, drop_fuels, group, method){ df <- df[,-which(names(df) %in% drop_cols)]
  df <- subset(df, !(Fuel %in% drop_fuels))
  df$Fuel <- as.factor(df$Fuel)
  y <- df[,which(names(df) ==target)]
  X = df[,which(names(df) != target)]
  preproc <- preProcess(X, method=method)
  X <- predict(preproc, newdata=X)
  df <- cbind(y, X)
  names(df)[names(df) == "y"] <- target
  return(df)
}
```
```{r, results="hide", echo=F, message=F}
SEED=123
data = read.csv(paste(PATH, "data/processed_data/socc_ndvi_postprocess.csv", sep="/"))

non_predictor_columns = c("Group", 
                          "AccSpeciesID",
                          "ndvi_time_lag",
                          "nearest_stid")
```
```{r}
data <- data[,-which(names(data) %in% c("X", "AccSpeciesID", "nearest_stid", "Group"))]
data = aggregate(.~Site + Fuel + Date, data=data, FUN=mean)
```
```{r}
drop_cols = c("Site", "Date", "station_distance") #Fields to exclude from processing
drop_fuels= c("Red Shank", "Manzanita, Eastwoods", "Brittlebrush") #Fuels to exclude from processing
method=c('knnImpute', 'YeoJohnson', 'center', 'scale') #preprocessing pipeline

inds <- partition(data$Fuel, p=c(train=0.8, test=0.2))
train <- data[inds$train,]
test <- data[inds$test,]

train <- process(train, target="Percent", drop_cols=drop_cols, drop_fuels=drop_fuels, group="Fuel", method=method)
test <- process(test, target="Percent", drop_cols=drop_cols, drop_fuels=drop_fuels, group="Fuel", method=method)
```
```{r}
group_vars = c("Site", "Fuel")
group_variables = list(
  # Fuel specific data
  "Fuel" = c(
      "14.0_mean", "15.0_mean", "40.0_mean", "46.0_mean", "47.0_mean", "48.0_mean",
      "50.0_mean", "51.0_mean", "53.0_mean", "55.0_mean", "56.0_mean", "58.0_mean",
      "144.0_mean", "186.0_mean", "410.0_mean", "572.0_mean", "978.0_mean", "3106.0_mean",
      "3109.0_mean", "3110.0_mean", "3112.0_mean", "3113.0_mean", "3114.0_mean", "3115.0_mean",
      "3116.0_mean", "3117.0_mean", "3120.0_mean", "3479.0_mean", "14.0_std", "15.0_std",
      "40.0_std", "46.0_std", "47.0_std", "48.0_std", "50.0_std", "51.0_std",
      "53.0_std", "55.0_std", "56.0_std", "58.0_std", "144.0_std", "186.0_std",
      "410.0_std", "572.0_std", "978.0_std", "3106.0_std", "3109.0_std", "3110.0_std",
      "3112.0_std", "3113.0_std", "3114.0_std", "3115.0_std", "3116.0_std", "3117.0_std",             
      "3120.0_std", "3479.0_std", "16.0", "37.0", "43.0", "154.0", "599.0", "3106.0"
        ),
  # Weather specific data
  "Site" = c()
)
```
```{r}
X = train %>% select(-Percent)# select(-non_predictor_columns, -Percent)
y = train$Percent
```
```{r, Prior Elicitation}
gseq= seq(.0005,2,length=10000)
X_matrix = data.matrix(X %>% select(-Fuel))
n = nrow(X_matrix)
p = ncol(X_matrix)
V= diag(p)
beta= rmvnorm(1000, sigma= V)
sse= colSums((X_matrix %*% t(beta))^2) / n
taus <- sapply(gseq, function(g) mean(sse * g / (1 + sse * g)))
prior_data <- data.frame(x=log(gseq), y=taus)
ggplot(prior_data) +
  geom_line(aes(x=x, y=y)) +
  xlab("log(g)") +
  ylab("tau") +
  scale_x_continuous(breaks = round(seq(-9, 0, by = 0.5),1)) +
  scale_y_continuous(breaks = round(seq(0, 1, by = 0.01),1)) +
  coord_cartesian(ylim=c(0,1)) +
  ggtitle("Prior elicitation of g") +
  theme_classic() 
```
```{r, include=F, echo=F}
runByFactor <- function(X, group) {
 stopifnot(group %in% group_vars) 
  
 result = list()
 factors <- levels(X[, "Fuel"])
 print("Reached")
 for (factor in factors) {
   # Subset the data by this factor
   print(factor)
   factor_indexes <- which(X[,group] == factor)
   print(factor_indexes)
   constant_vars <- as.vector(group_variables[[group]]) # 
   constant_vars <- constant_vars[constant_vars %in% names(X)]
   # browser()
   X_subset <-  X[factor_indexes,] %>% select(-Fuel)
                # select(-all_of(constant_vars)) %>% # Take out group variables, dates and group specific variables (like plant traits)
                # select(-station_distance)  #, -station_elevation)
   y_subset <- y[factor_indexes]
   
   # Check that X_subset has no NAs 
   stopifnot( rowSums(is.na(X_subset)) == 0)
   # Run the model selection
   out = modelSelection(y=y_subset, x=X_subset, priorCoef=zellnerprior(taustd = 1), priorDelta=modelbbprior(1,1), niter=10000)
   
   # Get the data out
   result[[factor]] = out
 }
 return(result)
}
result <- runByFactor(X, "Fuel")
```
```{r, check for convergence}
checkConvergence <- function(fuel_result, name) {
  nvars= rowSums(fuel_result$postSample)
  par(mar=c(4,5,.1,.1), cex.lab=1.3, cex.axis=1.3)
  png(str_interp(
    "${PATH}/analysis/results/convergence/${name}_convergence_modelsize.png"
  )) 
  plot(nvars, type='l', xlab='Gibbs iteration', ylab='Model size', main=name)
  dev.off()
  
  par(mar=c(4,5,.1,.1), cex.lab=1.3, cex.axis=1.3)
  
  
  png(str_interp(
    "${PATH}/analysis/results/convergence/${name}_convergence_posterior.png"
  )) 
  plot(fuel_result$postProb, type='l', xlab='Gibbs iteration', ylab='log p(y | gamma) + log p(gamma)', main=name)
  dev.off()
  
  margppest= matrix(NA,nrow=nrow(fuel_result$postSample),ncol=ncol(fuel_result$postSample))
  for (j in 1:ncol(fuel_result$postSample)) {
    margppest[,j]= cumsum(fuel_result$postSample[,j])/(1:nrow(fuel_result$postSample))
  }
  
  col= rep('black',length(beta))
  par(mar=c(4,5,.1,.1), cex.lab=1, cex.axis=1)
  
  png(str_interp(
    "${PATH}/analysis/results/convergence/${name}_convergence_margpp.png"
  )) 
  plot(margppest[,1], type='l', ylim=c(0,1), col=col[1], xlab='Gibbs iteration', ylab='Estimated P(gamma_j=1 | y)', main=name)
  for (j in 2:ncol(margppest)) lines(margppest[,j], col=col[j])
  dev.off()
}
for (fuel in levels(X$Fuel)) {
  checkConvergence(result[[fuel]], fuel)
}
```
```{r}
plot_margpp <- function(mombf_result_object, name, n=20) {
    factor_results <- data.frame( coef(mombf_result_object) )
    factor_results["varname"] = rownames(factor_results)
    gg_data <- factor_results %>% filter( !(varname %in% c("phi", "intercept")) )  %>% top_n(n, wt=margpp) %>% arrange(margpp)
    plot <- gg_data %>% ggplot() + geom_col(aes(x=margpp, y=reorder(varname, margpp), fill=estimate)) + xlim(0,1) +
                                theme_classic() + xlab("Marginal Posterior Probability") + ylab("Variable") + # TODO change
                                scale_fill_viridis(discrete = F) + 
                                theme(plot.title = element_text(hjust = 0.5)) + ggtitle(name)    
   filename = str_interp(
     "${PATH}/analysis/results/${name}_margpp_plot.png"
   )
   ggsave(filename=filename, plot=plot, device='png')
    return(plot)
}

analyse_data = function(result) {
  result_plots = list()
  for (factor in names(result) ) {
    plot <- plot_margpp(result[[factor]], factor)
    result_plots[[factor]] = plot
  }
  print(names(result_plots))
  return(result_plots)
}

plot_list <- analyse_data(result)
```
```{r}
# Display and visualise the data
factor <- "chamise"
result1 = result[[factor]]
factor_results <- data.frame( coef(result1) )
factor_results["varname"] = rownames(factor_results)

# How to filter the data so that you do not overplot.
gg_data <- factor_results %>% filter( !(varname %in% c("phi", "intercept")) )  %>% filter(margpp > 0.05) 
gg_data %>% ggplot() + geom_col(aes(x=margpp, y=varname, fill=estimate))
                          theme_classic() + xlab("Marginal Posterior Probability") + ylab("Variable") + # TODO change
                          theme(plot.title = element_text(hjust = 0.5)) + ggtitle(factor)
```
```{r}
#plot a lmer pred with PI values. can use ols predict(model, data, interval="confidence)
#pass result from either that or predictInterval(lmer.fit, data) to this function
# data <- df of 3 columns
#     fit <- estaimte
#     upr
#     lwr
plot_lmer_pred <- function(data, title){
  plot <- ggplot(data=data) +
    geom_point(mapping=aes(x=1:nrow(data), y = fit), size=1) +
    geom_point(mapping=aes(x=1:nrow(data), y = Percent), color="red", size=1) +
    geom_linerange(mapping=aes(x=1:nrow(data), ymin=lwr, ymax=upr), alpha=0.5) + # error bar change
    geom_hline(yintercept=79, linetype="dashed", color="blue") + 
    xlab("Observations") + ylab("Predictions and 95% PI") + 
    ggtitle(paste0("Predictions for ", title)) + theme_classic()
  return(plot)
}
plot_all_species <- function(pred, test, suffix){
  fitted <- cbind(pred, test)
  fuels <- as.character(distinct(fitted, Fuel)[,1])
  for (fuel in fuels){
    fitted_fuel <- subset(fitted, Fuel==fuel, select=c("Percent", "Fuel", "fit", "upr", "lwr"))
    plot <- plot_lmer_pred(fitted_fuel, fuel)
    ggsave(plot, file=paste0("analysis/results/pca/plot_", fuel, suffix, ".png"), width=14, height=10, units="cm")
  }
}
```
```{r}
d = data.frame(coef(result[["chamise"]])) %>% rownames_to_column(var="rownames") %>% filter( !(rownames %in%  c("phi", "intercept")) )
d = d %>% filter(margpp > 0) %>% select(-margpp) %>% rename("fit"="estimate", "lwr"="X2.5.", "upr"="X97.5.") %>% filter(abs(fit) > 0.1)
# plot_lmer_pred(d, "test")
d  %>% ggplot() + geom_point(aes(y=fit, x=rownames(d))) + geom_errorbar(aes(y=fit, x=rownames(d), ymin=lwr, ymax=upr)) + theme_classic()# + scale_y_continuous(trans="log2")
```
```{r, fig.width=20, fig.height=15}
color_dict = list(
"buckwheat, eastern mojave"="red",
"ceanothus, bigpod"="blue",
"ceanothus, hoaryleaf"="green",
"chamise"="orange",
"chamise, new growth"="purple",
"chamise, old growth"="brown",
"sage, black"="black",
"sage, purple"="yellow",
"sagebrush, black"="maroon",
"sagebrush, california"="turquoise"
)
plot <- ggplot()
add_factor = function(factor, plot) {
  d = data.frame(coef(result[[factor]])) %>% rownames_to_column(var="varnames") %>% filter( !(varnames %in%  c("phi", "intercept")) )
  d = d %>% filter(margpp > 0) %>% top_n(15, wt=margpp) %>% select(-margpp) %>% rename("fit"="estimate", "lwr"="X2.5.", "upr"="X97.5.") %>% filter(abs(fit) > 0.1)
  d_test = d %>% filter(lwr > 0 || upr < 0)
  if (nrow(d_test) > 0) {
    d = d_test
  } 
  plot <- plot + geom_errorbar(data=d, aes(y=fit, x=varnames, ymin=lwr, ymax=upr, color=color_dict[[factor]])) + geom_point(data=d, aes(y=fit, x=varnames, color=color_dict[[factor]]))
}
for (factor in levels(X$Fuel)[1:5]) {
  plot <- add_factor(factor, plot)
}
plot + xlab("Variables") + ylab("BMA Estimate") + coord_flip() + theme_classic()
```
```{r}
all_result = modelSelection(y=y, x=(X %>% select(-Fuel)), priorCoef=zellnerprior(taustd = 1), priorDelta=modelbbprior(1,1), niter=10000)
```

```{r}
checkConvergence(all_result, "all")
plot_margpp(all_result, "All Variables",  n=30)
```
```{r}
mombf_result_object <- result[["chamise"]]
factor_results <- data.frame( coef(mombf_result_object) )
factor_results["varname"] = rownames(factor_results)
gg_data <- factor_results %>% filter( !(varname %in% c("phi", "intercept")) )  %>% top_n(20, wt=margpp)
plot <- gg_data %>% ggplot() + geom_col(aes(x=margpp, y=varname, fill=estimate)) + xlim(0,1) +
                            theme_classic() + xlab("Marginal Posterior Probability") + ylab("Variable") + # TODO change
                            scale_fill_viridis(discrete = F) + 
                            theme(plot.title = element_text(hjust = 0.5)) + ggtitle(factor)    
plot
```